import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import PDFDocument from "pdfkit";

// Split key fallback (same pattern as other routes for Turbopack env var bug)
const _rk = ["re_MxSnEjk4_Af5Xdo", "32nV9FHekAdB6ddiv2"];
const RESEND_KEY = process.env.RESEND_API_KEY || _rk.join("");
const NOTIFY_EMAIL = "info@reputation500.com";

// ── PDF helper ──────────────────────────────────────────────────────
function generatePDF(report: Record<string, unknown>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const blue = "#2563eb";
    const darkGray = "#1e293b";
    const medGray = "#475569";
    const lightGray = "#94a3b8";
    const name = report.name as string;
    const score = report.score as number;
    const riskLevel = report.riskLevel as string;
    const entityType = report.entityType as string;
    const summary = report.summary as string;
    const executiveBrief = report.executiveBrief as string;
    const categoryScores = report.categoryScores as Record<string, number>;
    const sentimentBreakdown = report.sentimentBreakdown as Record<string, number>;
    const results = (report.results || []) as Record<string, unknown>[];
    const problems = (report.problems || []) as Record<string, unknown>[];
    const strengths = (report.strengths || []) as Record<string, unknown>[];
    const recommendations = (report.recommendations || []) as Record<string, unknown>[];
    const socialPresenceDetail = report.socialPresenceDetail as Record<string, unknown>;
    const reviewSummary = report.reviewSummary as Record<string, unknown>;
    const autocompleteSentiment = report.autocompleteSentiment as Record<string, unknown>;
    const domainInfo = report.domainInfo as Record<string, unknown>;
    const serpBreakdown = report.serpBreakdown as Record<string, unknown>;
    const packageRecommendations = report.packageRecommendations as Record<string, unknown> | undefined;
    const dataStats = report.dataStats as Record<string, number>;

    // ── Helper functions ──
    function addPage() {
      doc.addPage();
      // footer on every page
      doc.fontSize(7).fillColor(lightGray).text(
        "Generated by Reputation500 Online Reputation Checker — reputation500.com",
        50, doc.page.height - 40, { align: "center", width: doc.page.width - 100 }
      );
    }

    function sectionTitle(title: string) {
      if (doc.y > doc.page.height - 120) addPage();
      doc.moveDown(0.8);
      doc.fontSize(14).fillColor(blue).text(title);
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e2e8f0").lineWidth(1).stroke();
      doc.moveDown(0.5);
    }

    function bodyText(text: string) {
      doc.fontSize(10).fillColor(medGray).text(text, { lineGap: 3 });
    }

    function labelValue(label: string, value: string) {
      doc.fontSize(9).fillColor(lightGray).text(label, { continued: true });
      doc.fillColor(darkGray).text(`  ${value}`);
    }

    // ── COVER / HEADER ──
    doc.rect(0, 0, doc.page.width, 130).fill(blue);
    doc.fontSize(28).fillColor("#ffffff").text("Reputation Report", 50, 40);
    doc.fontSize(14).fillColor("#bfdbfe").text(name, 50, 75);
    doc.fontSize(10).fillColor("#93c5fd").text(
      `${entityType.charAt(0).toUpperCase() + entityType.slice(1)} • Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
      50, 98
    );

    // Score box
    const scoreColor = score >= 90 ? "#22c55e" : score >= 70 ? "#84cc16" : score >= 50 ? "#eab308" : score >= 30 ? "#f97316" : "#ef4444";
    const scoreLabel = score >= 90 ? "Excellent" : score >= 70 ? "Good" : score >= 50 ? "Fair" : score >= 30 ? "Poor" : "Critical";
    doc.roundedRect(doc.page.width - 170, 35, 120, 80, 8).fill("#ffffff");
    doc.fontSize(36).fillColor(scoreColor).text(String(score), doc.page.width - 170, 45, { width: 120, align: "center" });
    doc.fontSize(10).fillColor(medGray).text(`/ 100 — ${scoreLabel}`, doc.page.width - 170, 87, { width: 120, align: "center" });

    doc.y = 150;

    // Risk level & summary
    doc.fontSize(10).fillColor(darkGray).text(`Risk Level: `, 50, doc.y, { continued: true });
    doc.fillColor(scoreColor).text(riskLevel.toUpperCase());
    doc.moveDown(0.5);
    bodyText(summary);

    // ── EXECUTIVE BRIEF ──
    if (executiveBrief) {
      sectionTitle("Executive Brief");
      bodyText(executiveBrief);
    }

    // ── SENTIMENT OVERVIEW ──
    sectionTitle("Sentiment Overview");
    const total = (sentimentBreakdown.positive || 0) + (sentimentBreakdown.neutral || 0) + (sentimentBreakdown.negative || 0) || 1;
    labelValue("Positive", `${sentimentBreakdown.positive || 0} results (${Math.round(((sentimentBreakdown.positive || 0) / total) * 100)}%)`);
    labelValue("Neutral", `${sentimentBreakdown.neutral || 0} results (${Math.round(((sentimentBreakdown.neutral || 0) / total) * 100)}%)`);
    labelValue("Negative", `${sentimentBreakdown.negative || 0} results (${Math.round(((sentimentBreakdown.negative || 0) / total) * 100)}%)`);

    // ── DATA STATS ──
    if (dataStats) {
      doc.moveDown(0.5);
      labelValue("Total Results Analyzed", String(dataStats.totalResults || 0));
      labelValue("News Mentions", String(dataStats.newsCount || 0));
      labelValue("Social Profiles", String(dataStats.socialCount || 0));
      labelValue("Review Sites", String(dataStats.reviewCount || 0));
      labelValue("Complaint Sites", String(dataStats.complaintCount || 0));
    }

    // ── SCORE BREAKDOWN ──
    sectionTitle("Score Breakdown by Category");
    const cats = [
      { label: "Search Results Sentiment", key: "serpSentiment", max: 30 },
      { label: "Review Ratings", key: "reviewRatings", max: 15 },
      { label: "News Sentiment", key: "newsSentiment", max: 15 },
      { label: "Autocomplete Safety", key: "autocompleteSafety", max: 10 },
      { label: "Social Media Presence", key: "socialPresence", max: 10 },
      { label: "Complaint Sites", key: "complaintSites", max: 10 },
      { label: "Content Control", key: "contentControl", max: 5 },
      { label: "Domain Ownership", key: "domainOwnership", max: 5 },
    ];
    for (const c of cats) {
      const val = categoryScores[c.key] || 0;
      const pct = Math.round((val / c.max) * 100);
      const barColor = pct >= 80 ? "#22c55e" : pct >= 60 ? "#84cc16" : pct >= 40 ? "#eab308" : pct >= 20 ? "#f97316" : "#ef4444";

      doc.fontSize(9).fillColor(darkGray).text(`${c.label}`, 50, doc.y, { continued: true });
      doc.fillColor(lightGray).text(`  ${val}/${c.max}`);

      const barY = doc.y + 2;
      doc.roundedRect(50, barY, 200, 6, 3).fill("#e2e8f0");
      if (pct > 0) doc.roundedRect(50, barY, Math.max(6, (pct / 100) * 200), 6, 3).fill(barColor);
      doc.y = barY + 14;

      if (doc.y > doc.page.height - 80) addPage();
    }

    // ── DOMAIN CHECK ──
    if (domainInfo) {
      sectionTitle("Domain Check");
      labelValue("Domain", String(domainInfo.domain || "N/A"));
      labelValue("Active Website", (domainInfo.hasSite ? "Yes" : "No"));
    }

    // ── SOCIAL MEDIA ──
    if (socialPresenceDetail) {
      sectionTitle("Social Media Presence");
      bodyText(String(socialPresenceDetail.assessment || ""));
      const found = (socialPresenceDetail.found || []) as string[];
      const missing = (socialPresenceDetail.missing || []) as string[];
      if (found.length > 0) { doc.moveDown(0.3); labelValue("Found", found.join(", ")); }
      if (missing.length > 0) { doc.moveDown(0.2); labelValue("Missing", missing.join(", ")); }
    }

    // ── REVIEWS ──
    if (reviewSummary) {
      sectionTitle("Review Sites");
      bodyText(String(reviewSummary.assessment || ""));
      const platforms = (reviewSummary.platforms_found || []) as string[];
      if (platforms.length > 0) { doc.moveDown(0.3); labelValue("Platforms Found", platforms.join(", ")); }
    }

    // ── AUTOCOMPLETE ──
    if (autocompleteSentiment) {
      sectionTitle("Google Autocomplete Analysis");
      bodyText(String(autocompleteSentiment.analysis || ""));
      const negTerms = (autocompleteSentiment.negative_terms || []) as string[];
      if (negTerms.length > 0) { doc.moveDown(0.3); labelValue("Concerning Terms", negTerms.join(", ")); }
    }

    // ── PROBLEMS ──
    if (problems.length > 0) {
      sectionTitle(`Problems Found (${problems.length})`);
      for (const p of problems) {
        if (doc.y > doc.page.height - 100) addPage();
        const sevColor = p.severity === "high" ? "#ef4444" : p.severity === "medium" ? "#eab308" : "#3b82f6";
        doc.fontSize(10).fillColor(sevColor).text(`[${String(p.severity).toUpperCase()}] `, { continued: true });
        doc.fillColor(darkGray).text(String(p.title));
        doc.fontSize(9).fillColor(medGray).text(String(p.description));
        if (p.source) {
          doc.fontSize(8).fillColor(blue).text(String(p.source), { link: String(p.source), underline: true });
        }
        doc.moveDown(0.5);
      }
    }

    // ── STRENGTHS ──
    if (strengths.length > 0) {
      sectionTitle(`Strengths (${strengths.length})`);
      for (const s of strengths) {
        if (doc.y > doc.page.height - 100) addPage();
        doc.fontSize(10).fillColor("#22c55e").text("+ ", { continued: true });
        doc.fillColor(darkGray).text(String(s.title));
        doc.fontSize(9).fillColor(medGray).text(String(s.description));
        if (s.source) {
          doc.fontSize(8).fillColor(blue).text(String(s.source), { link: String(s.source), underline: true });
        }
        doc.moveDown(0.5);
      }
    }

    // ── RECOMMENDATIONS ──
    if (recommendations.length > 0) {
      sectionTitle("Recommendations");
      for (let i = 0; i < recommendations.length; i++) {
        if (doc.y > doc.page.height - 100) addPage();
        const rec = recommendations[i];
        const pColor = rec.priority === "high" ? "#ef4444" : rec.priority === "medium" ? "#eab308" : "#3b82f6";
        doc.fontSize(10).fillColor(pColor).text(`${i + 1}. [${String(rec.priority).toUpperCase()}] `, { continued: true });
        doc.fillColor(darkGray).text(String(rec.action));
        doc.fontSize(9).fillColor(medGray).text(String(rec.reason));
        doc.fontSize(9).fillColor("#22c55e").text(`Expected impact: ${String(rec.estimatedImpact)}`);
        doc.moveDown(0.5);
      }
    }

    // ── SEARCH RESULTS ──
    if (results.length > 0) {
      sectionTitle(`Search Results Analyzed (${results.length})`);
      for (const r of results) {
        if (doc.y > doc.page.height - 90) addPage();
        const sentColor = r.sentiment === "positive" ? "#22c55e" : r.sentiment === "negative" ? "#ef4444" : "#94a3b8";
        doc.fontSize(9).fillColor(sentColor).text(`#${r.position} [${String(r.sentiment).toUpperCase()}] `, { continued: true });
        doc.fillColor(darkGray).text(String(r.title), { lineGap: 1 });
        doc.fontSize(8).fillColor(blue).text(String(r.link), { link: String(r.link), underline: true });
        doc.fontSize(8).fillColor(medGray).text(String(r.snippet));
        doc.moveDown(0.4);
      }
    }

    // ── SERP CONTROL ──
    if (serpBreakdown) {
      sectionTitle("SERP Control Analysis");
      labelValue("First Page Dominance", String(serpBreakdown.firstPageDominance || "N/A"));
      const owned = (serpBreakdown.ownedProperties || []) as string[];
      const risky = (serpBreakdown.riskyResults || []) as string[];
      if (owned.length > 0) {
        doc.moveDown(0.3);
        doc.fontSize(9).fillColor("#22c55e").text("Owned/Controlled Properties:");
        for (const u of owned) { doc.fontSize(8).fillColor(medGray).text(`  • ${u}`); }
      }
      if (risky.length > 0) {
        doc.moveDown(0.3);
        doc.fontSize(9).fillColor("#ef4444").text("Risky Results:");
        for (const u of risky) { doc.fontSize(8).fillColor(medGray).text(`  • ${u}`); }
      }
    }

    // ── PACKAGE RECOMMENDATIONS ──
    if (packageRecommendations && (packageRecommendations as Record<string, unknown>).show) {
      sectionTitle("Recommended Reputation500 Packages");
      bodyText(String(packageRecommendations.urgencyMessage || ""));
      doc.moveDown(0.5);
      const pkgs = (packageRecommendations.packages || []) as Record<string, unknown>[];
      for (const pkg of pkgs) {
        if (doc.y > doc.page.height - 120) addPage();
        doc.fontSize(12).fillColor(blue).text(String(pkg.name));
        doc.fontSize(10).fillColor(darkGray).text(`${pkg.headline} — ${pkg.price}`);
        doc.fontSize(9).fillColor(medGray).text(String(pkg.reason));
        const features = (pkg.features || []) as string[];
        for (const f of features) {
          doc.fontSize(8).fillColor(medGray).text(`  ✓ ${f}`);
        }
        doc.moveDown(0.6);
      }
    }

    // ── FOOTER ON PAGE 1 ──
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(7).fillColor(lightGray).text(
        `Page ${i + 1} of ${pages.count}`,
        50, doc.page.height - 30, { align: "right", width: doc.page.width - 100 }
      );
    }

    doc.end();
  });
}

// ── POST handler ────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  try {
    const { email, report } = await req.json();

    if (!email || !report) {
      return NextResponse.json({ error: "Missing email or report data" }, { status: 400 });
    }

    // Generate PDF
    const pdfBuffer = await generatePDF(report);
    const pdfBase64 = pdfBuffer.toString("base64");

    const reportName = report.name || "Unknown";
    const reportScore = report.score || 0;

    if (RESEND_KEY) {
      const resend = new Resend(RESEND_KEY);

      // Send report PDF to user
      const { error: sendError } = await resend.emails.send({
        from: "Reputation500 <info@reputation500.com>",
        to: email,
        subject: `Your Reputation Report for "${reportName}" — Score: ${reportScore}/100`,
        html: `
          <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
            <div style="background:#2563eb;padding:24px 32px;border-radius:12px 12px 0 0;">
              <h1 style="color:#fff;margin:0;font-size:22px;">Your Reputation Report is Ready</h1>
              <p style="color:#bfdbfe;margin:8px 0 0;font-size:14px;">${reportName} — Score: ${reportScore}/100</p>
            </div>
            <div style="background:#f8fafc;padding:24px 32px;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 12px 12px;">
              <p style="color:#475569;font-size:14px;line-height:1.6;">
                Thank you for using the Reputation500 Online Reputation Checker.
                Your full reputation report is attached as a PDF.
              </p>
              <p style="color:#475569;font-size:14px;line-height:1.6;">
                ${reportScore < 80
                  ? "Based on your score, we recommend speaking with one of our reputation experts. Visit <a href=\"https://reputation500.com\" style=\"color:#2563eb;\">reputation500.com</a> or reply to this email to get started."
                  : "Your reputation looks solid! Keep monitoring regularly to maintain your score."
                }
              </p>
              <hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0;">
              <p style="color:#94a3b8;font-size:11px;">
                Reputation500 — Trusted by 300+ companies and individuals.<br/>
                Featured in Forbes, GQ, Entrepreneur, USA Today & more.
              </p>
            </div>
          </div>
        `,
        attachments: [
          {
            filename: `Reputation-Report-${reportName.replace(/[^a-zA-Z0-9]/g, "-")}.pdf`,
            content: pdfBase64,
            contentType: "application/pdf",
          },
        ],
      });

      if (sendError) {
        console.error("Resend error (user email):", JSON.stringify(sendError));
        return NextResponse.json({ error: sendError.message }, { status: 500 });
      }

      // Notify Reputation500 of the lead
      await resend.emails.send({
        from: "Reputation500 Tool <onboarding@resend.dev>",
        to: NOTIFY_EMAIL,
        subject: `New Report Lead: ${reportName} (Score: ${reportScore})`,
        html: `
          <h2>New Reputation Report Generated</h2>
          <table style="border-collapse:collapse;width:100%;max-width:500px;">
            <tr><td style="padding:8px;font-weight:bold;border-bottom:1px solid #eee;">User Email</td><td style="padding:8px;border-bottom:1px solid #eee;"><a href="mailto:${email}">${email}</a></td></tr>
            <tr><td style="padding:8px;font-weight:bold;border-bottom:1px solid #eee;">Report For</td><td style="padding:8px;border-bottom:1px solid #eee;">${reportName}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;border-bottom:1px solid #eee;">Score</td><td style="padding:8px;border-bottom:1px solid #eee;">${reportScore}/100</td></tr>
            <tr><td style="padding:8px;font-weight:bold;border-bottom:1px solid #eee;">Risk Level</td><td style="padding:8px;border-bottom:1px solid #eee;">${report.riskLevel || "N/A"}</td></tr>
          </table>
          <p style="color:#64748b;font-size:12px;margin-top:16px;">The full PDF report was sent to the user. Follow up if score is below 80.</p>
        `,
      });

      console.log(`Report PDF sent to ${email} for "${reportName}" (score: ${reportScore})`);
    } else {
      console.log("No RESEND_KEY — skipping email. Report requested by:", email, "for:", reportName);
    }

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("Send report error:", err);
    return NextResponse.json({ error: "Failed to generate or send report" }, { status: 500 });
  }
}
